version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "20:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
    - 7.13.8
  - dependency-name: sass
    versions:
    - 1.32.0
    - 1.32.5
  - dependency-name: "@google-cloud/translate"
    versions:
    - 6.0.5
  - dependency-name: "@reduxjs/toolkit"
    versions:
    - 1.5.0
